import mongoose from "mongoose";

export const storePrefixSchema = new mongoose.Schema(
    {
        grnPrefix: { type: String, default: "GRN" },
        rmBoGrnPrefix: { type: String, default: "GRN-RM" },
        fgGrnPrefix: { type: String, default: "GRN-FG" },
        poPrefix: { type: String, default: "PO" },
        incomingPoPrefix: { type: String, default: "PO-IN" },
        outgoingPoPrefix: { type: String, default: "PO-OUT" },
        outwardPoPrefix: { type: String, default: "PO-OUT" },
        dcPrefix: { type: String, default: "DC" },
        invoicePrefix: { type: String, default: "INV" },
        partPrefix: { type: String, default: "PART" },
        categoryPrefix: { type: String, default: "CAT" },
        vendorPrefix: { type: String, default: "VEN" },
        customerPrefix: { type: String, default: "CUS" },
        jobWorkSupplierPrefix: { type: String, default: "JWS" },
        incomingRfqPrefix: { type: String, default: "RFQ-IN" },
        outgoingRfqPrefix: { type: String, default: "RFQ-OUT" },
        quotationOutwardPrefix: { type: String, default: "QT-OUT" },
        quotationInwardPrefix: { type: String, default: "QT-IN" },
        exchangeRates: {
            USD: { type: Number, default: 86.80 },
            EUR: { type: Number, default: 92.50 },
            GBP: { type: Number, default: 108.20 },
            AED: { type: Number, default: 23.63 },
            CAD: { type: Number, default: 61.50 },
            AUD: { type: Number, default: 55.40 },
            SGD: { type: Number, default: 64.20 },
            JPY: { type: Number, default: 0.56 },
            CNY: { type: Number, default: 11.95 },
        },
        timeLockPolicies: {
            grn: { type: Number, default: 24 },
            customerPo: { type: Number, default: 24 },
            deliveryChallan: { type: Number, default: 24 },
            invoice: { type: Number, default: 24 },
            purchasePo: { type: Number, default: 24 },
            jobWorkChallan: { type: Number, default: 24 },
            rfqQuotation: { type: Number, default: 24 },
            mrbDisposition: { type: Number, default: 24 },
        },
        approvalSettings: {
            materialRequest: {
                enabled: { type: Boolean, default: false },
                allowAllUsers: { type: Boolean, default: true },
                approvers: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
                approverNames: [{ type: String }],
            },
            outwardPo: {
                enabled: { type: Boolean, default: false },
                allowAllUsers: { type: Boolean, default: true },
                approvers: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
                approverNames: [{ type: String }],
            },
        },
    },
    { timestamps: true }
);
