"use client";

import React, { useState, useEffect } from 'react';
import LoadingSpinner from '@/src/components/LoadingSpinner';
import { API_BASE_URL } from '@/src/utils/config';
import { Hash, Tag, ShoppingCart, FileText, CheckCircle2, Save } from 'lucide-react';

interface PrefixSettings {
  customerPrefix: string;
  vendorPrefix: string;
  jobWorkSupplierPrefix: string;
  categoryPrefix: string;
  partPrefix: string;
  incomingPoPrefix: string;
  outwardPoPrefix?: string;
  outgoingPoPrefix: string;
  poPrefix: string;
  incomingRfqPrefix: string;
  outgoingRfqPrefix: string;
  quotationOutwardPrefix: string;
  quotationInwardPrefix: string;
  invoicePrefix: string;
  dcPrefix: string;
  grnPrefix: string;
  rmBoGrnPrefix: string;
  fgGrnPrefix: string;
}

export default function PrefixSettingsPage() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [settings, setSettings] = useState<PrefixSettings>({
    customerPrefix: 'CUS',
    vendorPrefix: 'VEN',
    jobWorkSupplierPrefix: 'JWS',
    categoryPrefix: 'CAT',
    partPrefix: 'PART',
    incomingPoPrefix: 'PO-IN',
    outwardPoPrefix: 'PO-OUT',
    outgoingPoPrefix: 'PO-OUT',
    poPrefix: 'PO',
    incomingRfqPrefix: 'RFQ-IN',
    outgoingRfqPrefix: 'RFQ-OUT',
    quotationOutwardPrefix: 'QT-OUT',
    quotationInwardPrefix: 'QT-IN',
    invoicePrefix: 'INV',
    dcPrefix: 'DC',
    grnPrefix: 'GRN',
    rmBoGrnPrefix: 'GRN-RM',
    fgGrnPrefix: 'GRN-FG',
  });

  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  useEffect(() => {
    fetchPrefixSettings();
  }, []);

  const fetchPrefixSettings = async () => {
    try {
      setLoading(true);
      const token = localStorage.getItem('token');
      const res = await fetch(`${API_BASE_URL}/api/store/prefix`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      if (res.ok) {
        const data = await res.json();
        if (data.settings) {
          setSettings(prev => ({ ...prev, ...data.settings }));
        }
      }
    } catch (error) {
      console.error('Failed to fetch prefix settings:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (field: keyof PrefixSettings, value: string) => {
    setSettings(prev => ({ ...prev, [field]: value.toUpperCase() }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      setSaving(true);
      setMessage(null);
      const token = localStorage.getItem('token');
      const res = await fetch(`${API_BASE_URL}/api/store/prefix`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(settings)
      });

      const data = await res.json();
      if (res.ok) {
        setMessage({ type: 'success', text: 'Prefix settings updated successfully!' });
        alert('Prefix settings saved successfully!');
      } else {
        throw new Error(data.message || 'Failed to save prefix settings');
      }
    } catch (error: any) {
      console.error('Error saving prefix settings:', error);
      setMessage({ type: 'error', text: error.message || 'Failed to save prefix settings' });
      alert(`Error saving settings: ${error.message || 'Failed to save prefix settings'}`);
    } finally {
      setSaving(false);
    }
  };

  if (loading) return <LoadingSpinner />;

  const renderSectionHeader = (title: string, icon: React.ReactNode, colorClass: string = "bg-indigo-600") => (
    <h3 className="text-base font-semibold text-gray-900 mb-4 flex items-center gap-2">
      <div className={`p-1.5 rounded-lg text-white ${colorClass}`}>
        {icon}
      </div>
      {title}
    </h3>
  );

  return (
    <div className="w-full min-h-full flex-1 space-y-6 pb-12 transition-all duration-300">
      <div className="w-full space-y-6">
        {/* Header Banner */}
        <div className="w-full bg-white dark:bg-gray-900 p-4 sm:p-6 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div className="flex-1">
            <h1 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
              <Hash className="text-indigo-600 dark:text-indigo-400 h-5 w-5 sm:h-6 sm:w-6" />
              Autogenerated Code Prefix Settings
            </h1>
            <p className="text-xs sm:text-sm text-gray-500 dark:text-gray-400 mt-1">
              Configure custom prefix formats for autogenerated IDs across Customers, Vendors, POs, RFQs, Invoices, DCs, and GRNs.
            </p>
          </div>
          <button
            onClick={handleSubmit}
            disabled={saving}
            className="w-full md:w-auto flex items-center justify-center gap-2 px-6 py-2.5 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 text-white font-semibold rounded-xl shadow-md transition-all disabled:opacity-50 text-sm shrink-0 cursor-pointer"
          >
            <Save size={18} />
            {saving ? 'Saving...' : 'Save All Prefixes'}
          </button>
        </div>

        {message && (
          <div className={`w-full p-4 rounded-xl text-sm font-medium flex items-center gap-2 ${message.type === 'success' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800' : 'bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-400 border border-red-200 dark:border-red-800'}`}>
            <CheckCircle2 size={18} />
            {message.text}
          </div>
        )}

        <form onSubmit={handleSubmit} className="w-full space-y-6">
          {/* Section 1: Master Entities */}
          <div className="w-full bg-white dark:bg-gray-900 p-4 sm:p-6 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm space-y-4">
            {renderSectionHeader("Master Entity Prefixes", <Tag size={18} />, "bg-indigo-600")}
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5 gap-4 sm:gap-6">
              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Customer Prefix</label>
                <input
                  type="text"
                  value={settings.customerPrefix || ''}
                  onChange={e => handleChange('customerPrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. CUS"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: CUS-001</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Vendor Prefix</label>
                <input
                  type="text"
                  value={settings.vendorPrefix || ''}
                  onChange={e => handleChange('vendorPrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. VEN"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: VEN-001</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Job Work Supplier Prefix</label>
                <input
                  type="text"
                  value={settings.jobWorkSupplierPrefix || ''}
                  onChange={e => handleChange('jobWorkSupplierPrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. JWS"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: JWS-001</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Category Prefix</label>
                <input
                  type="text"
                  value={settings.categoryPrefix || ''}
                  onChange={e => handleChange('categoryPrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. CAT"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: CAT-ABC-1234</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Item / Part Prefix</label>
                <input
                  type="text"
                  value={settings.partPrefix || ''}
                  onChange={e => handleChange('partPrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. PART"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: PART-001</span>
              </div>
            </div>
          </div>

          {/* Section 2: Purchasing & RFQ Prefixes */}
          <div className="w-full bg-white dark:bg-gray-900 p-4 sm:p-6 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm space-y-4">
            {renderSectionHeader("Purchasing & RFQ Prefixes", <ShoppingCart size={18} />, "bg-purple-600")}
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5 gap-4 sm:gap-6">
              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Incoming PO Prefix</label>
                <input
                  type="text"
                  value={settings.incomingPoPrefix || ''}
                  onChange={e => handleChange('incomingPoPrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. PO-IN"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: PO-IN-2026-001</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Outward PO Prefix</label>
                <input
                  type="text"
                  value={settings.outwardPoPrefix || settings.outgoingPoPrefix || settings.poPrefix || ''}
                  onChange={e => {
                    handleChange('outwardPoPrefix', e.target.value);
                    handleChange('outgoingPoPrefix', e.target.value);
                    handleChange('poPrefix', e.target.value);
                  }}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. PO-OUT"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: PO-OUT-2026-001</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Incoming RFQ Prefix</label>
                <input
                  type="text"
                  value={settings.incomingRfqPrefix || ''}
                  onChange={e => handleChange('incomingRfqPrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. RFQ-IN"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: RFQ-IN-2026-001</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Outgoing RFQ / Quotation Outward</label>
                <input
                  type="text"
                  value={settings.outgoingRfqPrefix || settings.quotationOutwardPrefix || ''}
                  onChange={e => {
                    handleChange('outgoingRfqPrefix', e.target.value);
                    handleChange('quotationOutwardPrefix', e.target.value);
                  }}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. QT-OUT"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: QT-OUT-2026-001</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Inward Quotation Prefix</label>
                <input
                  type="text"
                  value={settings.quotationInwardPrefix || ''}
                  onChange={e => handleChange('quotationInwardPrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. QT-IN"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: QT-IN-2026-001</span>
              </div>
            </div>
          </div>

          {/* Section 3: Operations & Billing Prefixes */}
          <div className="w-full bg-white dark:bg-gray-900 p-4 sm:p-6 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm space-y-4">
            {renderSectionHeader("Sales, DC & Billing Prefixes", <FileText size={18} />, "bg-emerald-600")}
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5 gap-4 sm:gap-6">
              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Invoice Number Prefix</label>
                <input
                  type="text"
                  value={settings.invoicePrefix || ''}
                  onChange={e => handleChange('invoicePrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. INV"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: INV-2026-001</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">Delivery Challan (DC) Prefix</label>
                <input
                  type="text"
                  value={settings.dcPrefix || ''}
                  onChange={e => handleChange('dcPrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. DC"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: DC-2026-001</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">RM / BO Items GRN Prefix</label>
                <input
                  type="text"
                  value={settings.rmBoGrnPrefix || settings.grnPrefix || ''}
                  onChange={e => {
                    handleChange('rmBoGrnPrefix', e.target.value);
                    handleChange('grnPrefix', e.target.value);
                  }}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. GRN-RM"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: GRN-RM/20260808-120000</span>
              </div>

              <div className="flex flex-col">
                <label className="block text-xs font-bold text-gray-700 dark:text-gray-300 mb-1.5">FG Items GRN Prefix</label>
                <input
                  type="text"
                  value={settings.fgGrnPrefix || ''}
                  onChange={e => handleChange('fgGrnPrefix', e.target.value)}
                  className="w-full px-4 py-2.5 bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:bg-white dark:focus:bg-gray-900 text-sm font-semibold transition-all text-gray-900 dark:text-white"
                  placeholder="e.g. GRN-FG"
                />
                <span className="text-[11px] text-gray-400 dark:text-gray-500 mt-1 block">Format: GRN-FG/20260808-120000</span>
              </div>
            </div>
          </div>

          <div className="flex justify-end pt-2">
            <button
              type="submit"
              disabled={saving}
              className="w-full sm:w-auto flex items-center justify-center gap-2 px-8 py-3 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 text-white font-semibold rounded-xl shadow-lg shadow-indigo-200 dark:shadow-none transition-all disabled:opacity-50 text-sm cursor-pointer"
            >
              <Save size={18} />
              {saving ? 'Saving Settings...' : 'Save Prefix Settings'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
